# Generated by Django 3.2.10 on 2022-06-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallets',
            name='mnemonic',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='wallets',
            name='sk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='wallets',
            name='wallet',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
