# Generated by Django 3.2.10 on 2022-06-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220603_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallets',
            name='avatar',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
