# Generated by Django 3.2.10 on 2022-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wallets_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallets',
            name='avatar',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='avatar',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
