# Generated by Django 3.2.10 on 2022-06-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_wallets_invoiceimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='envVariables',
            field=models.TextField(null=True),
        ),
    ]
