# Generated by Django 3.2.10 on 2022-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_useraccount_envvariables'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_variable', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='envVariables',
        ),
    ]
