# Generated by Django 3.2.10 on 2022-06-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220614_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvVariables',
        ),
    ]
