# Generated by Django 3.2.10 on 2022-06-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_envvariables'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='costumer_id',
            field=models.IntegerField(null=True),
        ),
    ]
